### PR TITLE
[IN-0] Preinstall java 11 as users requested

### PR DESCRIPTION
**Pull request by fehersanyi-bitrise**
### Pull Request Checklist

Check/accept these:

- [ ] I've updated the version in the Dockerfile
- [ ] I've updated the CHANGELOG.md
- [ ] I've provided a link or explanation below which describes the changes in the tool itself

`Copy or link the tool's changelog here`

### CODE REVIEW

**Review by peterheja-bitrise — APPROVED** [review]
The changeset is okay, but I'm not 100% sure we should add java11 to LTS, at least in our current standing with android LTS.
But, I like that we add it.

So ,yeah, overall, LGTM.

**Comment by fehersanyi-bitrise** [comment]
meh
```
Step 5/22 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-11-jdk
 ---> Running in f1c3bbd9f43f
Reading package lists...
Building dependency tree...
Reading state information...
Package openjdk-11-jdk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```
I'm not sure if it worth the research wdyt @bitrise-tom @peterheja-bitrise ?

**Comment by peterheja-bitrise** [comment]
> meh
> 
> ```
> Step 5/22 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-11-jdk
>  ---> Running in f1c3bbd9f43f
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package openjdk-11-jdk is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> ```
> 
> I'm not sure if it worth the research wdyt @bitrise-tom @peterheja-bitrise ?

Oh, yeah, the `apt-get update` was left out.

**Review by peterheja-bitrise — CHANGES_REQUESTED** [review]
`apt-get update` is missing

**Comment by fehersanyi-bitrise** [comment]
> `apt-get update` is missing

That is on live 7 actually 🧐

**Comment by peterheja-bitrise** [comment]
> > `apt-get update` is missing
> 
> That is on live 7 actually 🧐

Yeah, but then you add a new repo, therefore the old cache is stale.

**Review by peterheja-bitrise — APPROVED** [review]
LGTM

**Review by bitrise-tom — APPROVED** [review]

**Pull request merged**
